### PR TITLE
Use the PATH environment variable to find package managers

### PR DESCRIPTION
**Pull request by ivonunes**

### CODE REVIEW

**Comment by silvernode** [comment]
Well this was unexpected

**Comment by logenkain** [comment]
I'm don't quite understand your do-while loop.
This is what I gather:
"p" becomes a pointer to ":" or NULL, whichever it finds.

Then, assuming "p" is not NULL, p[0] = 0 -- Why? What does this do?

Then at the end, "s = p + 1" Which is where I get a bit more confused.
From the way I read it, "s" stops pointing to the envpath and points to ": + 1", or possibly "1".

Appreciate the work, I'll test it shortly and probably merge it soon, I'm just trying to learn how this all works, thanks.

**Comment by logenkain** [comment]
Oh, and what is this doing in logenlib.h?

char** str_split(char* a_str, const char a_delim);

**Comment by ivonunes** [comment]
Disclaimer: I'm a web developer and my explanation for anything C-related might become confusing and/or turn out to be rubbish.

1. strchr tries to find the first occurrence of ":", and we store it in p.
2. If there was a match, we want to extract the string just up until that point. We've now got p[0] pointing to the ":", so p[0] = 0 turns it into the string terminator.
3. From now on we get back to using s, which contains our proper string. As we've changed the first ":" to the string terminator, the string will cut off at that point, giving us exactly what we need: the first path in the string.
4. s = p + 1. We pick up at the string terminator we set earlier, and go forward one character, essentially removing the path we just processed from the string.
5. Repeat until there are no more characters left.

As for str_split, that's simple enough: I initially put that function in logenlib, then deleted it and forgot to get rid of the declaration in the header file :)

**Pull request merged**
